import json
import os

# 1. 定义牛津102花卉映射字典（变量名必须是cat_to_name）
cat_to_name = {
    "1": ["pink primrose", "粉报春"],
    "2": ["hard-leaved pocket orchid", "硬叶兜兰"],
    "3": ["canterbury bells", "风铃草"],
    "4": ["sweet pea", "香豌豆"],
    "5": ["english marigold", "英国金盏花"],
    "6": ["tiger lily", "虎皮百合"],
    "7": ["moon orchid", "月光兰"],
    "8": ["bird of paradise", "天堂鸟"],
    "9": ["monkshood", "乌头"],
    "10": ["globe thistle", "蓝刺头"],
    "11": ["snapdragon", "金鱼草"],
    "12": ["colt's foot", "款冬"],
    "13": ["king protea", "帝王海神花"],
    "14": ["spear thistle", "矛蓟"],
    "15": ["yellow iris", "黄鸢尾"],
    "16": ["globe flower", "金莲花"],
    "17": ["purple coneflower", "紫锥花"],
    "18": ["peruvian lily", "秘鲁百合"],
    "19": ["balloon flower", "桔梗"],
    "20": ["giant white arum lily", "巨型白海芋"],
    "21": ["fire lily", "火百合"],
    "22": ["pincushion flower", "针垫花"],
    "23": ["fritillary", "贝母"],
    "24": ["red ginger", "红姜花"],
    "25": ["grape hyacinth", "葡萄风信子"],
    "26": ["corn poppy", "虞美人"],
    "27": ["prince of wales feathers", "威尔士亲王羽"],
    "28": ["stemless gentian", "无茎龙胆"],
    "29": ["artichoke", "洋蓟"],
    "30": ["sweet william", "须苞石竹"],
    "31": ["carnation", "康乃馨"],
    "32": ["garden phlox", "园天蓝绣球"],
    "33": ["love in the mist", "黑种草"],
    "34": ["mexican aster", "墨西哥紫菀"],
    "35": ["alpine sea holly", "高山海石竹"],
    "36": ["ruby-lipped cattleya", "红唇卡特兰"],
    "37": ["cape flower", "海角花"],
    "38": ["great masterwort", "大欧白芷"],
    "39": ["siam tulip", "暹罗郁金香"],
    "40": ["lenten rose", "圣诞玫瑰"],
    "41": ["barbeton daisy", "巴伯顿雏菊"],
    "42": ["daffodil", "水仙"],
    "43": ["sword lily", "唐菖蒲"],
    "44": ["poinsettia", "一品红"],
    "45": ["bolero deep blue", "波莱罗深蓝"],
    "46": ["wallflower", "桂竹香"],
    "47": ["marigold", "金盏菊"],
    "48": ["buttercup", "毛茛"],
    "49": ["oxeye daisy", "牛眼菊"],
    "50": ["common dandelion", "普通蒲公英"],
    "51": ["petunia", "矮牵牛"],
    "52": ["wild pansy", "野三色堇"],
    "53": ["primula", "报春花"],
    "54": ["sunflower", "向日葵"],
    "55": ["pelargonium", "天竺葵"],
    "56": ["bishop of llandaff", "兰达夫主教"],
    "57": ["gaura", "山桃草"],
    "58": ["geranium", "老鹳草"],
    "59": ["orange dahlia", "橙色大丽花"],
    "60": ["pink-yellow dahlia", "粉黄大丽花"],
    "61": ["cautleya spicata", "穗花姜"],
    "62": ["japanese anemone", "秋明菊"],
    "63": ["black-eyed susan", "黑心菊"],
    "64": ["silverbush", "银布什"],
    "65": ["californian poppy", "加州罂粟"],
    "66": ["osteospermum", "蓝眼菊"],
    "67": ["spring crocus", "春番红花"],
    "68": ["bearded iris", "有髯鸢尾"],
    "69": ["windflower", "银莲花"],
    "70": ["tree poppy", "树罂粟"],
    "71": ["gazania", "勋章菊"],
    "72": ["azalea", "杜鹃花"],
    "73": ["water lily", "睡莲"],
    "74": ["rose", "玫瑰"],
    "75": ["thorn apple", "曼陀罗"],
    "76": ["morning glory", "牵牛花"],
    "77": ["passion flower", "西番莲"],
    "78": ["lotus", "莲花"],
    "79": ["toad lily", "蟾蜍百合"],
    "80": ["anthurium", "红掌"],
    "81": ["frangipani", "鸡蛋花"],
    "82": ["clematis", "铁线莲"],
    "83": ["hibiscus", "木槿"],
    "84": ["columbine", "耧斗菜"],
    "85": ["desert-rose", "沙漠玫瑰"],
    "86": ["tree mallow", "树锦葵"],
    "87": ["magnolia", "玉兰花"],
    "88": ["cyclamen", "仙客来"],
    "89": ["watercress", "豆瓣菜"],
    "90": ["canna lily", "美人蕉"],
    "91": ["hippeastrum", "朱顶红"],
    "92": ["bee balm", "美国薄荷"],
    "93": ["pink quill", "粉羽毛"],
    "94": ["foxglove", "毛地黄"],
    "95": ["bougainvillea", "三角梅"],
    "96": ["camellia", "山茶花"],
    "97": ["mallow", "锦葵"],
    "98": ["mexican petunia", "墨西哥矮牵牛"],
    "99": ["bromelia", "凤梨"],
    "100": ["blanket flower", "天人菊"],
    "101": ["trumpet creeper", "凌霄花"],
    "102": ["blackberry lily", "射干"]
}

# 2. 保存路径
save_path = r"F:\bird--CNN\data_flowers\dataset\cat_to_name.json"

# 3. 创建文件夹
folder_path = os.path.dirname(save_path)
if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"📁 已创建文件夹：{folder_path}")

# 4. 保存文件（变量名必须是cat_to_name）
with open(save_path, "w", encoding="utf-8") as f:
    json.dump(cat_to_name, f, ensure_ascii=False, indent=2)

print(f"✅ 文件已生成：{save_path}")